version: "3.7"

services:
  app:
    image: gendosu/multistage-example
    build:
      context: .
      target: app
      cache_from: 
        - "gendosu/multistage-example-builder"
        - "gendosu/multistage-example-package"